services:
  garderie:
    image: yassinsiouda/garderie:0.60
    build: .
    ports:
      - "8050:5000"
    volumes:
      - ./data/sites:/sites
      - ./data/pb_data:/pb_data
      - ./data/pb_hooks:/pb_hooks
    environment:
      - PB_ADMIN_EMAIL=${PB_ADMIN_EMAIL}
      - PB_ADMIN_PASSWORD=${PB_ADMIN_PASSWORD}
      - SHELL_USER=${SHELL_USER}
      - SHELL_PASSWORD=${SHELL_PASSWORD}
    env_file:
      - .env
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "0.5"
    restart: unless-stopped
