[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log

[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:rclone-webdav]
command=rclone serve webdav /sites --addr 127.0.0.1:%(ENV_WEBDAV_PORT)s --user %(ENV_SHELL_USER)s --pass %(ENV_SHELL_PASSWORD)s
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:pocketbase]
command=pocketbase serve --http 0.0.0.0:%(ENV_PB_PORT)s --dir /pb_data --hooksDir /pb_hooks
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
